version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      BUILD_DIR: build
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y clang cmake ninja-build gdb
      - run:
          name: Configure
          command: |
            mkdir -p build
            cmake -S . -B build \
              -G Ninja \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPAW_STRESS=0
      - run:
          name: Build
          command: cmake --build build --config Debug
      - run:
          name: Test
          working_directory: build
          command: ctest --verbose --build-config Debug

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

