name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [
          ubuntu-latest, 
          macos-latest, 
          # windows-latest
        ]
        build_type: [Debug, Release]
        cc: [
         // gcc, 
          clang, 
         // cl
          ]
        stress: [0, 2]
        exclude:
#          - os: windows-latest
#            cc: gcc
#          - os: windows-latest
#            cc: clang
          - os: ubuntu-latest
            cc: cl
          - os: macos-latest
            cc: cl
    
    env:
      build_dir: "${{ github.workspace }}/build"
      
    steps:
    - uses: actions/checkout@v3


    - name: Install LLVM (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y zlib1g-dev llvm-19 llvm-19-dev clang-19 lld-19

    - name: Install LLVM (macOS)
      if: runner.os == 'macOS'
      run: brew install llvm

    - name: Install LLVM (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: choco install llvm --yes

    - name: Configure
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          LLVM_DIR=/usr/lib/llvm-19/lib/cmake/llvm
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          LLVM_DIR=$(brew --prefix llvm)/lib/cmake/llvm
        else
          LLVM_DIR="C:/Program Files/LLVM/lib/cmake/llvm"
        fi

        cmake -S . -B build -DLLVM_DIR="$LLVM_DIR"

    - name: Configure
      run: >
        cmake -S "${{ github.workspace }}" -B "${{ env.build_dir }}"
        -DCMAKE_C_COMPILER=${{ matrix.cc }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DPAW_STRESS=${{ matrix.stress }}
        
    - name: Build
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --config ${{ matrix.build_type }} --target paw_test

#    - name: Test
#      working-directory: ${{ env.build_dir }}
#      run: ctest --verbose --build-config ${{ matrix.build_type }}


