name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [
          ubuntu-latest, 
          macos-latest, 
          #windows-latest
        ]
        build_type: [Debug, Release]
        include:
          - cc: clang
            cxx: clang++
          #- cc: gcc
          #  cxx: g++
          #- cc: cl
          #  cxx: cl
        stress: [0, 2]
        #exclude:
        #  - os: windows-latest
        #    cc: gcc
        #  - os: windows-latest
        #    cc: clang
        #  - os: ubuntu-latest
        #    cc: cl
        #  - os: macos-latest
        #    cc: cl
    
    env:
      build_dir: "${{ github.workspace }}/build"
      LLVM_VERSION: 19
      
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && \
        sudo apt-get install -y clang cmake llvm-${LLVM_VERSION}-dev && \
        sudo apt-get clean && \
        sudo rm -rf /var/lib/apt/lists/*           

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install llvm@${{ env.LLVM_VERSION }}

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: choco install llvm --yes

    - name: Configure
      shell: bash
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          LLVM_DIR="/usr/lib/llvm-${{ env.LLVM_VERSION }}/lib/cmake/llvm"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          LLVM_DIR="$(brew --prefix llvm@${{ env.LLVM_VERSION }})/lib/cmake/llvm"
        else
          LLVM_DIR="C:/Program Files/LLVM/lib/cmake/llvm"
        fi
        cmake -B ${{ env.build_dir }} -G Ninja \
            -DPAW_CLANG_PATH=/usr/bin/clang \
            -DPAW_STRESS=${{ matrix.stress }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DLLVM_DIR="${LLVM_DIR}"

    - name: Build
      working-directory: ${{ env.build_dir }}
      run: |
        cmake --build . --parallel

    - name: Test
      working-directory: ${{ env.build_dir }}
      run: ctest --verbose

