name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
        cc: [gcc, clang, cl]
        stress: [0, 2]
        exclude:
          - os: windows-latest
            cc: gcc
          - os: windows-latest
            cc: clang
          - os: ubuntu-latest
            cc: cl
          - os: macos-latest
            cc: cl
    
    env:
      build_dir: "${{ github.workspace }}/build"
      
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: >
        cmake -S "${{ github.workspace }}" -B "${{ env.build_dir }}"
        -DCMAKE_C_COMPILER=${{ matrix.cc }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DPAW_STRESS=${{ matrix.stress }}
        
    - name: Build
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ env.build_dir }}
      run: ctest --build-config ${{ matrix.build_type }}


